### ISSUE TITLE
`iterrr` macro removed.

### ISSUE THREAD

**Issue by dxxb** [hamidb80/iterrr#32]
`iterrr` was removed by 1ceb97922b0a700d2144b98c427f21617cac795f. Is it possible to have it back or implement it in my own code using symbols exported from the `iterrr` module? I used to be able to write stuff like this:

``` nim
      dest = something.iterator.iterrr:
        map: do_something(it) # do_something
        map: do_something_else(it) # do_something_else
        toSeq()
```

and loved it 😄 . Thank you!

**Comment by hamidb80** [comment]
hey, I thought it was not very useful to write `iterrr` everywhere, so I removed it.

back then this style was possible:
```nim
(3..6).iterrr:
  filter(it > 3)
  map(n => n - 2)
  each(n):
    acc.add n
```

do think it worth to bring it back?

Another style that I can think of is:
```nim
|>(3..6):
  filter(it > 3)
  .map(n => n - 2)
  .sum()
```

**Comment by hamidb80** [comment]
here you go:
https://github.com/hamidb80/iterrr/#iterrr-macro

**Comment by dbrignoli** [comment]
Hi!

My reasons for preferring `iterrr` to `|>` are:
1. I try to avoid operators that are not well known. Seeing `.iterrr` makes it (much?) easier for people not familiar with the `iterrr` library to know that it must be something imported from the `iterrr` module. If I saw `|>` and didn't know about `iterrr` it would slow down my parsing of the code I am reading.
2. I liked I could to break up the a "transform pipeline" into indented lines like `op: details`. I found it compact and more readable compared to the parenthesised version `.op(details)`

**Comment by dbrignoli** [comment]
> here you go: https://github.com/hamidb80/iterrr/#iterrr-macro

Thank you! I will check it out ASAP 😄

**Comment by hamidb80** [comment]
> 2\. I liked I could to break up the a "transform pipeline" into indented lines like `op: details`. I found it compact and more readable compared to the parenthesised version `.op(details)`

the negative side of `op: fn(it)` is that you cannot name arguments like `map((x, y) => x+y)`

**Comment by dbrignoli** [comment]
It works like a charm, thank you.

> the negative side of `op: fn(it)` is that you cannot name arguments like `map((x, y) => x+y)`

Yes, I found that out when I first started using `iterrr` but being able to pick one style or the other depending on what fits the  situation is still great despite having to give up renaming args.

**Comment by hamidb80** [comment]
> It works like a charm, thank you.
> 
> > the negative side of `op: fn(it)` is that you cannot name arguments like `map((x, y) => x+y)`
> 
> Yes, I found that out when I first started using `iterrr` but being able to pick one style or the other depending on what fits the situation is still great despite having to give up renaming args.

hey, just checked out that you can ignore pars in `iterrr` macro version, likeL
```nim
import iterrr

let points = @[(1, 2), (-3, 4), (12, 3), (-1, -6), (5, -9)]
points.items.iterrr:
  map (x, y) => x
  filter it > 0
  each n:
    echo n
```

**Comment by dxxb** [comment]
> that's pretty neat in my opinion.

Indeed! Thank you for documenting this. FYI I have added support for nestable `.iterrr:` calls on a my fork's dev branch and I am looking to see if it's possible to add support for naming args like this `map: (x, y) => x+y`. See https://github.com/dxxb/iterrr/commits/dev and https://github.com/dxxb/iterrr/commit/0a6d4447a90526d2c045f16917e6334346f4b091
